/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ConvertTextBody {
  /** @minLength 1 */
  text: string;
  /** @minLength 1 */
  persona: string;
  /** @minLength 1 */
  language: string;
  /** @minLength 1 */
  languageSection: string;
  /** @minLength 1 */
  tone: string;
}

export interface ConvertTextResponse {
  variations: string[];
}
